config/routes.rb
Rails.application.routes.draw do
  get 'actions/reunite'

  resources :reports do
    member do
      post "remove_reunited"
    end
  end
  root to: "pages#index"
  get "/about", to: "pages#about"
  get "/flyer", to: "pages#flyer"
  get "/terms", to: "pages#terms"
  get "/resources", to: "pages#resources"
  patch "/reunite/:id", to: "actions#reunite", as: 'reunite'
  post "/reunite_form/:id", to: "actions#reunite_form", as: 'reunite_form'

end

app/models/report.rb
class Report < ActiveRecord::Base
  has_attached_file :photo,
    styles: {
      thumb: "140x140#",
      medium: "500x500>",
    },
    :convert_options => {
      :medium => "-strip -quality 90 -interlace Plane",
    }

  belongs_to :animal_type
  delegate :name, to: :animal_type, prefix: true, allow_nil: true

  belongs_to :location
  delegate :name, to: :location, prefix: true, allow_nil: true

  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\Z/
  validates_with AttachmentSizeValidator,
    attributes: :photo,
    less_than: 10.megabytes

  validates :report_type, :summary, :reporter_name, :reporter_contact_info, :animal_type,
    presence: true

  validates :summary, length: { maximum: 40 }

  validates :reuniter_name, :reuniter_email, presence: true,
    unless: proc {|r|
      (r.changed & %w{reunited reuniter_email reuniter_name}).empty? ||
        !r.reunited
    }
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :set_report, only: [:show, :edit, :update, :destroy]

  http_basic_authenticate_with(
    name: "admin",
    password: ENV.fetch("ADMIN_PASSWORD"),
    except: [:index, :show, :new, :create]
  )

  # GET /reports
  # GET /reports.json
  def index
    @reports = Report.reorder("reports.created_at desc").includes(:animal_type)
    @reports = apply_filters @reports
    respond_to do |format|
      format.html { @reports = apply_pagination @reports }
      format.csv do
        render text: csv_content(@reports),
          content_type: "text/csv; charset=utf-8; header=present"
      end
    end
  end

  # GET /reports/1
  # GET /reports/1.json
  def show
  end

  # GET /reports/new
  def new
    @report = Report.new
  end

  # GET /reports/1/edit
  def edit
  end

  # POST /reports
  # POST /reports.json
  def create
    raise "Disabled"
    @report = Report.new(report_params)

    respond_to do |format|
      if @report.save
        format.html { redirect_to @report, notice: 'Report was successfully created.' }
        format.json { render :show, status: :created, location: @report }
      else
        format.html { render :new }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reports/1
  # PATCH/PUT /reports/1.json
  def update
    respond_to do |format|
      attrs = admin_report_params

      if !@report.reunion_confirmed && attrs[:reunion_confirmed]
        @report.reunion_confirmed_at = Time.now
      end

      if @report.update(attrs)
        format.html { redirect_to @report, notice: 'Report was successfully updated.' }
        format.json { render :show, status: :ok, location: @report }
      else
        format.html { render :edit }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reports/1
  # DELETE /reports/1.json
  def destroy
    @report.destroy
    respond_to do |format|
      format.html { redirect_to reports_url, notice: 'Report was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def remove_reunited
    @report = Report.find params[:id]
    attrs = {
      reunited: nil,
      reunited_at: nil,
      reuniter_is_reporter: nil,
      reuniter_name: nil,
      reuniter_email: nil,
      reuniter_comment: nil,
    }
    if @report.update_attributes(attrs)
      redirect_to @report, notice: 'Report is no longer reunited.'
    else
      render 'reports/edit'
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_report
      @report = Report.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def report_params
      params.require(:report).permit(
        :summary,
        :description,
        :location_id,
        :report_type,
        :reporter_name,
        :reporter_contact_info,
        :reporter_email,
        :photo,
        :animal_type_id,
      )
    end

    def admin_report_params
      admin_params = params.require(:report).permit(
        :reunion_confirmed,
        :reunion_confirmed_by,
        :reunion_confirmation_notes,
      )
      report_params.merge(admin_params)
    end

    require 'csv'
    def csv_content(reports)
      columns1 = %w{
        id
        report_type
      }
      columns2 = %w{
        summary
        description
        reporter_name
        reporter_contact_info
        created_at
        updated_at
        photo_file_name
        photo_content_type
        photo_file_size
        photo_updated_at
      }
      columns3 = %w{
        reunited
        reuniter_is_reporter
        reuniter_name
        reunited_at
        reuniter_comment
      }
      reports = reports.
        includes(:animal_type, :location)

      CSV.generate do |csv|
        csv << (
          columns1.map(&:humanize) +
          ["Animal type name", "Location name"] +
          columns2.map(&:humanize) +
          ["Photo URL"] +
          columns3.map(&:humanize)
        )
        reports.each do |report|
          csv << (
            columns1.map {|column| report.send(column) } +
            [report.animal_type_name, report.location_name] +
            columns2.map {|column| report.send(column) } +
            [(report.photo.url(:medium) if report.photo.present?)] +
            columns3.map {|column| report.send(column) }
          )
        end
      end
    end

    def apply_filters(query)
      reports = Report.arel_table
      # Warning: O(n*m) conditions: n=words, m=fields
      if params[:words].present?
        words = params[:words].split(/\W/) # A word is alphanum or "_"
        query = words.inject(query) do |ch, word|
          fields = [:summary, :description, :reporter_name]
          conds = fields.map {|f| reports[f].matches("%#{word}%") }
          disjunction = conds.inject(conds.pop) do |disj, cond|
            disj.or(cond)
          end
          ch.where(disjunction)
        end
      end
      if params[:report_type].present?
        query = query.where(report_type: params[:report_type].to_s)
      end
      if params[:reunited].present?
        matching_values = params[:reunited] == "true" ? true : [false, nil]
        query = query.where(reunited: matching_values)
      end
      if params[:reunion_confirmed].present?
        matching_values =
          params[:reunion_confirmed] == "true" ?  true : [false, nil]
        query = query.where(reunion_confirmed: matching_values)
      end
      if params[:animal_type_id].present?
        animal_type_id = params[:animal_type_id].to_s
        animal_type_id = nil if animal_type_id == "none"
        query = query.where(animal_type_id: animal_type_id)
      end
      if params[:location_id].present?
        location_id = params[:location_id].to_s
        location_id = nil if location_id == "none"
        query = query.where(location_id: location_id)
      end
      query
    end

    def apply_pagination(query)
      query.page(params[:page]).per(30)
    end
end

app/views/reports/_form.html.erb
<%= form_for(@report, html: { class: "form-horizontal"}) do |f| %>
  <%= render "form_fields", f: f %>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-8">
      <p class="help-block">
        Please Review Carefully:  You will be not able to edit after creating
        the report.
      </p>
      <%= f.submit class: "btn btn-primary" %>
      <%= link_to 'View all reports', reports_path, class: "btn btn-link" %>
      <% if @report.persisted? %>
        <%= link_to 'Show', @report, class: "btn btn-link" %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/reports/_form_fields.html.erb
  <% if @report.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@report.errors.count, "error") %> prohibited this report from being saved:</h2>

      <ul>
      <% @report.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-8">
      <div class="radio">
        <%= f.label :report_type_found do %>
          <%= f.radio_button :report_type, "found" %>
          I <strong>found</strong> an animal (that does not belong to me)
        <% end %>
      </div>
      <div class="radio">
        <%= f.label :report_type_lost do %>
          <%= f.radio_button :report_type, "lost" %>
          I <strong>lost</strong> an animal due to the fire
        <% end %>
      </div>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :summary, class: "col-sm-2 control-label" %>
    <div class="col-sm-8">
      <%= f.text_field :summary, class: "form-control" %>
      <p class="help-block">
        Please include kennel/location, animal name, and Lake County
        ID, if available.
      </p>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :animal_type, class: "col-sm-2 control-label" %>
    <div class="col-sm-8">
      <%= f.collection_radio_buttons(:animal_type_id, AnimalType.all, :id, :name) do |button| %>
        <div class="radio">
          <%= button.label do %>
            <%= button.radio_button %>
            <%= button.text %>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :description, class: "col-sm-2 control-label" %>
    <div class="col-sm-8">
      <%= f.text_area :description, class: "form-control", rows: 5 %>
      <p class="help-block">
        Please include details such as:
      </p>
      <ul class="help-block">
        <li>the town the animal was lost or found in
        <li>the animal's breed
        <li>coat color(s) and pattern
        <li>eye color
        <li>distinctive markings
        <li>gender
        <li>name
        <li>neuter status
        <li>length of tail
        <li>date found/lost (otherwise we only track date reported here)
        <li>collar color and type
      </ul>
      <p class="help-block">
        When re-posting from Facebook, please include a link to the
        original post, not just the page it was shared on.  (Eventually
        it will get pushed off the bottom of the page it was shared
        on.)
      </p>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :location, "Originating location",
      class: "col-sm-2 control-label" %>
    <div class="col-sm-8">
      <%= f.collection_select(:location_id, Location.all, :id, :name,
                              { include_blank: "unknown" },
                              class: "form-control") %>
      <p class="help-block">
        Please select the location that the animal was originally found
        (if found) or where it was lost from (if lost).
      </p>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :reporter_name, class: "col-sm-2 control-label" %>
    <div class="col-sm-8">
      <%= f.text_field :reporter_name, class: "form-control" %>
      <p class="help-block">
        Please enter your name.  If you are reposting from another source,
        please indicate both your name and the original reporter's name if
        available.  For example: "Jane Doe via Joe Schmoe" if Jane was the
        original reporter and Joe is reposting it here.
      </p>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :reporter_contact_info, class: "col-sm-2 control-label" %>
    <div class="col-sm-8">
      <%= f.text_area :reporter_contact_info, class: "form-control" %>
      <p class="help-block">
        This will be displayed <strong>publicly</strong> so
        that others may respond to your report.  Suggested forms of
        contact: email, twitter, or phone.  Your residential address
        is not recommended.  If re-posting or posting on behalf of
        someone else, please include a contact for the original
        reporter.
      </p>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :reporter_email, class: "col-sm-2 control-label" %>
    <div class="col-sm-8">
      <%= f.text_field :reporter_email, class: "form-control" %>
      <p class="help-block">
        Please include an email so that we may easily contact you with
        follow-up correspondence regarding your report.  This will be
        kept <strong>private</strong> and will not be displayed
        publicly.
      </p>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :photo, class: "col-sm-2 control-label" %>
    <div class="col-sm-8">
      <%= f.file_field :photo %>
      <p class="help-block">
        Please avoid unpleasant or haunting photos of injured animals.
        If you get an error after uploading for 15-30 sec, try
        resizing your photo to ~800x800 pixels first.
      </p>
    </div>
  </div>

app/views/reports/edit.html.erb
<div class="page-header">
  <h1>Editing Report</h1>
</div>

<%= form_for(@report, html: { class: "form-horizontal"}) do |f| %>
  <%= render "form_fields", f: f %>

  <div class="form-group">
    <%= f.label :reunited, class: "col-sm-2 control-label" %>
    <div class="col-sm-8">
      <p class="form-control-static">
        <%= @report.reunited? ? "Yes" : "No" %>
      </p>
    </div>
  </div>

  <% if @report.reunited? %>
    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-8">
        <div class="checkbox">
          <%= f.label :reunion_confirmed do %>
            <%= f.check_box :reunion_confirmed %>
            The reunion has been confirmed by a trusted party by
            contacting the original poster or owner.
          <% end %>
        </div>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :reunion_confirmed_by, class: "col-sm-2 control-label" %>
      <div class="col-sm-8">
        <%= f.text_field :reunion_confirmed_by, class: "form-control" %>
      </div>
    </div>

    <div class="row">
      <div class="col-sm-2 field-label">
        <%= f.label :reunion_confirmed_at, class: "col-sm-2 control-label" %>
      </div>
      <div class="col-sm-8">
        <p class="form-control-static">
          <%= @report.reunion_confirmed_at.
                try(:strftime, "%A, %B %-d, %Y at %l:%M %P") %>
        </p>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :reunion_confirmation_notes,
        class: "col-sm-2 control-label" %>
      <div class="col-sm-8">
        <%= f.text_area :reunion_confirmation_notes, class: "form-control" %>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-8">
      <%= f.submit class: "btn btn-primary" %>
      <div class="pull-right">
        <%= link_to 'Remove Reunited Status', remove_reunited_report_path(@report),
              method: :post,
              class: "btn btn-warning #{"disabled" unless @report.reunited}",
              data: {
                confirm: "Are you sure you want to clear the reuniter fields? "+
                  "There is no undo."
              } %>
        <%= link_to 'Destroy', @report, method: :delete,
              class: "btn btn-danger",
              data: {
                confirm: "Are you sure you want to delete this report? "+
                  "There is no undo."
              } %>
      </div>
    </div>
  </div>
<% end %>

app/views/reports/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Reports</h1>

<p>
  Please
  <%= mail_to "mc-valley-fire-animals@oak.homeunix.org",
         "email me",
         subject: "Valley Fire Animals: " %>
  to update or remove a report.
</p>

<h2 style="font-size: 150%">Search</h2>

<div class="report-search" style="margin-bottom: 2em">
  <%= form_tag({}, method: :get,
               class: "form-inline"
               ) do %>
    <div style="margin-top: 0.5em">
      <div class="form-group">
        <%= label_tag :report_type %>
        <%
          choices = %w{lost found}.map {|t| [t.titleize, t] }
        %>
        <%= select_tag :report_type,
              options_for_select(choices, params[:report_type]),
              include_blank: "either",
              class: "form-control" %>
      </div>
      <div class="form-group">
        <%= label_tag :animal_type_id %>
        <%
          choices = AnimalType.all.map {|a| [a.name, a.id] }
          choices.unshift ["none specified", "none"]
        %>
        <%= select_tag :animal_type_id,
              options_for_select(choices, params[:animal_type_id]),
              include_blank: "any",
              class: "form-control" %>
      </div>
      <br class="hidden-xs hidden-md hidden-lg">
      <div class="form-group">
        <%= label_tag :location_id %>
        <%
          choices = Location.all.map {|a| [a.name, a.id] }
          choices.unshift ["none specified", "none"]
        %>
        <%= select_tag :location_id,
              options_for_select(choices, params[:location_id]),
              include_blank: "any",
              class: "form-control" %>
      </div>
      <br class="hidden-xs">
      <div class="form-group">
        <%= label_tag :reunited %>
        <%
          choices = [
            ["Yes", true],
            ["No", false],
          ]
        %>
        <%= select_tag :reunited,
              options_for_select(choices, params[:reunited]),
              include_blank: "either",
              class: "form-control" %>
      </div>
      <div class="form-group">
        <%= label_tag :words %>
        <%= text_field_tag :words, params[:words], class: "form-control" %>
      </div>
      <%= submit_tag "Search", class: "btn btn-primary" %>
    <% end %>
  </div>
  <div class="clearfix"></div>
</div>

<div style="margin-bottom: 0.5em; margin-top: 0.5em">
  <%= link_to 'New Report', new_report_path,
    class: "btn btn-primary" %>

  <p class="pull-right">
    <%= page_entries_info @reports %>
  </p>
</div>


<table class="table table-striped">
  <thead>
    <tr>
      <th>Reported</th>
      <th>Report type</th>
      <th>Animal type</th>
      <th>Summary</th>
      <th>Photo</th>
      <th>Description</th>
      <th>Reporter name</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @reports.each do |report| %>
      <tr>
        <td><%= report.created_at.strftime("%b %-d %l:%M %P") %></td>
        <td>
          <%= report.report_type %>
          <%= "REUNITED" if report.reunited %>
        </td>
        <td><%= report.animal_type_name %></td>
        <td><%= report.summary %></td>
        <td>
          <% if report.photo.present? %>
            <%= image_tag(report.photo.url(:thumb)) %>
          <% end %>
        </td>
        <td>
          <% more_link = link_to("[read&nbsp;more]".html_safe, report) %>
          <%= truncate(h(report.description),
                       omission: " " + more_link,
                       escape: false,
                       length: 150) %>
        </td>
        <td><%= report.reporter_name %></td>
        <td><%= link_to 'View Details', report %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<nav class="pagination-wrapper">
  <%= paginate @reports, theme: 'twitter-bootstrap-3' %>
</nav>

<p class="text-center">
  Export <%= pluralize @reports.total_count, "matching record" %> to
  <%= link_to "CSV", format: :csv %>
</p>

app/views/reports/new.html.erb
<div class="page-header">
  <h1>New Report</h1>
</div>

<div class="alert alert-warning" role="alert">
  Submission of new reports is disabled due to abusive submissions.
</div>

<%= render 'form' %>

app/views/reports/show.html.erb
<div class="page-header">
  <h1>Report <%= @report.id %></h1>
  <% if @report.reunited %>
    <h2>This animal has been returned home.</h2>
  <% end %>
</div>

<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col-sm-2 field-label">
    Summary
  </div>
  <div class="col-sm-8">
    <strong>
      <%= @report.report_type.titleize %> <%= @report.animal_type_name %>:
    </strong>
    <%= @report.summary %>
  </div>
</div>

<div class="row">
  <div class="col-sm-2 field-label">
    Reported
  </div>
  <div class="col-sm-8">
    <%= @report.created_at.strftime("%A, %B %-d, %Y at %l:%M %P") %>
  </div>
</div>

<div class="row">
  <div class="col-sm-2 field-label">
    Description
  </div>
  <div class="col-sm-8">
    <%= @report.description %>
  </div>
</div>

<div class="row">
  <div class="col-sm-2 field-label">
    Originating location
  </div>
  <div class="col-sm-8">
    <%= @report.location_name %>
  </div>
</div>

<div class="row">
  <div class="col-sm-2 field-label">
    Reporter name
  </div>
  <div class="col-sm-8">
    <%= @report.reporter_name %>
  </div>
</div>

<div class="row">
  <div class="col-sm-2 field-label">
    Reporter contact info
  </div>
  <div class="col-sm-8">
    <%= @report.reporter_contact_info %>
  </div>
</div>

<div class="row">
  <div class="col-sm-2 field-label">
    Photo
  </div>
  <div class="col-sm-8">
    <% if @report.photo.present? %>
      <%= image_tag(@report.photo.url(:medium)) %>
    <% end %>
  </div>
</div>

<div class="row">
  <div class="col-sm-2 field-label">
    Reunited?
  </div>
  <div class="col-sm-8">
    <%= @report.reunited ? "Yes" : "No" %>
    <% if @report.reunited %>
      <p>
        <strong>We've been told this animal is reunited with its owner.</strong>
        If this is incorrect, please <%= mail_to "mc-valley-fire-animals@oak.homeunix.org",
              "notify us",
               subject: "Valley Fire Animals: " %> and we will fix the report ASAP.
      </p>
    <% else %>
      <p>
        Have you reunited this animal with its owner?
        <br>
        <%= button_to 'Let us know!', reunite_form_path,
          class: 'btn btn-small btn-primary', role: "button" %>
      </p>
    <% end %>
  </div>
</div>

<% if @report.reunited? %>
  <div class="row">
    <div class="col-sm-2 field-label">
      Reunited at
    </div>
    <div class="col-sm-8">
      <%= @report.reunited_at.strftime("%A, %B %-d, %Y at %l:%M %P") %>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-2 field-label">
      Reuniter name
    </div>
    <div class="col-sm-8">
      <%= @report.reuniter_name %>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-2 field-label">
      Reuniter comment
    </div>
    <div class="col-sm-8">
      <%= @report.reuniter_comment %>
    </div>
  </div>
<% end %>

<br>
<%= link_to 'View all reports', reports_path %>